### ISSUE TITLE
(defvar suppress-values?) makes trouble in clozure-cl

### ISSUE THREAD

**Issue by OlafMerkert** [vsedach/Parenscript#1]
```
(defvar suppress-values?)
```

 in clozure-cl leaves `suppress-values?` unbound (as documented in Hyperspec). This leads to a "non-specific warning" when going through the parenscript tutorial

I guess the desired behaviour would be to have `nil` as default value (this fixes the error for me):

```
(defvar suppress-values? nil)
```

Best regards,
Olaf

**Comment by jasom** [comment]
Interestingly enough, my PR for improving multiple-value support also addresses this, as `suppress-values?` is no longer used.

**Comment by vsedach** [comment]
This was fixed in 31b5c0e0ce827d04a050903e5fd9a6f1890f5ea5
