### ISSUE TITLE
The function PARENSCRIPT::BODY is undefined.

### ISSUE THREAD

**Issue by mpsyco** [vsedach/Parenscript#15]
My code is broken since that  commit: 8d7e8fa1ce2e1a3115776af2ffc703d368171ef0 (I used ```git bisect``` to find which commit broke my code).

Here is the minimal code (that I found) to reproduce:

```lisp
(ps
  (let* ((errorp "NIL"))))
```

**Comment by mpsyco** [comment]
P.S. I don't have this error with the Parenscript from quicklisp, but I have this error with Parenscript from github (master of this repo).

**Comment by mpsyco** [comment]
@agrostis You did this commit, maybe you could find the source faster than anyone else :stuck_out_tongue: ?

**Comment by agrostis** [comment]
> @agrostis You did this commit, maybe you could find the source faster than anyone else :stuck_out_tongue: ?

Yes, I'm afraid it's my fault. My commit made the occurence of the macro WITH-DECLARATION-EFFECTS in the special operator handler for SYMBOL-MACROLET precede the macro definition. I'll post a patch in a minute.

> P.S. I don't have this error with the Parenscript from quicklisp, but I have this error with Parenscript from github (master of this repo).

Quicklisp uses the release version of Parenscript (v. 2.5). It might be time to release an updated version, but the decision is up to @vsedach.

**Comment by mpsyco** [comment]
Thanks! It broke my new and shiny feature, I was kind of sad :disappointed_relieved:
Can't wait for the fix :)

**Comment by mpsyco** [comment]
Ok, I will test it right away

**Comment by mpsyco** [comment]
Works
If I knew you were about to merge this I would've wait 2 minutes instead of adding your repo in my remotes :stuck_out_tongue:

**Comment by agrostis** [comment]
8 min. ago it was only in my own fork. Please re-pull now.

**Comment by mpsyco** [comment]
Pulled from vsedach/Parenscript master. Worked like a charm, thanks again.

**Comment by mpsyco** [comment]
> 8 min. ago it was only in my own fork.

I know, that's what I was saying by "adding your repo in my remotes". I added your fork to my remotes and tested with the branch "devel".
