### ISSUE TITLE
eql is undefined

### ISSUE THREAD

**Issue by StrmSrfr** [vsedach/Parenscript#18]
Attempting to pass `eql` as a parameter compiles fine but leads to a runtime error in the generated JavaScript.  It seems like it should just work. I'm not sure what the right fix is.

Adding a simple `(defun eql (x y) (eql x y))` to my code fixes this, but I don't think users should have to do that.
  Also, the documentation says not to use `eql` as the name of a function, so that might be breaking the rules.

 We could add `eql` to `*ps-lisp-library*`, but that seems weird.

The compiler could generate an anonymous function when `eql` appears out of operator position, but then `window["eql"]` would still be undefined, which I guess it shouldn't be.

I'm open to ideas and willing to implement the right solution if we can figure out what it is.

**Comment by jasom** [comment]
Parenscript does not define any new functions by intent; one ought to be able to add any expression or statement generated by parenscript into the middle of vanilla javascript and have it work.

So, if we were going to support this, putting it in *ps-lisp-library* would make the most sense, as that's where it ought to go if it were desired.

**Comment by vsedach** [comment]
>
> The compiler could generate an anonymous function when eql appears out of
> operator position, but then window["eql"] would still be undefined, which
> I guess it shouldn't be.
>
I have to take a look at my notes to see the details, but the "generate
anonymous function" technique is what I was leaning towards last time I
thought about this issue.
