### ISSUE TITLE
loop macro bug

### ISSUE THREAD

**Issue by erikronstrom** [vsedach/Parenscript#21]
These two loops generate the same javascript output:
(loop while (a) do (b)))
(loop do (b) while (a)))

=> (function () {
    while (a()) {
        b();
    };
})();

However, they loops are not equivalent. The former tests the condition before the loop, but the latter tests the condition /after/ the loop, so (b) is called at least once.

Regards
Erik

CL-USER 781 > (ps (loop while (a) do (b)))
"(function () {
    while (a()) {
        b();
    };
})();"

CL-USER 782 > (ps (loop do (b) while (a)))
"(function () {
    while (a()) {
        b();
    };
})();"

**Comment by agrostis** [comment]
This has been taken care of in a002169c6f514d1ebb6ab985ae58e877760c764e, as far as I understand. If you're using Quicklisp, I suggest that you fetch the repository version of Parenscript to a local project until either all these recent changes get released, or QL switches to the repo for its source.
