### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jasom** [vsedach/Parenscript#26]
I spoke with Zach about getting an updated parenscript in quicklisp, and he indicated that he typically waits for a new release.  Any chance of this happening?

**Comment by agrostis** [comment]
On Jan 28, 2016 08:03, "Jason Miller" <notifications@github.com> wrote:
>
> I spoke with Zach about getting an updated parenscript in quicklisp, and
he indicated that he typically waits for a new release. Any chance of this
happening?

I also think a release is overdue.

-- B. Sm.

**Comment by jasom** [comment]
Then if nobody objects within a week, I'll make a 2.6 release.

**Comment by vsedach** [comment]
Sounds good.

**Comment by jasom** [comment]
https://github.com/vsedach/Parenscript/releases/tag/v2.6

**Comment by jasom** [comment]
@vsedach Do you have access to the common-lisp.net project?  Xach says he fetches parenscript from http://common-lisp.net/project/parenscript/release/parenscript-latest.tgz

**Comment by vsedach** [comment]
Yes. I can ask the admin to add your common-lisp.net account if you have
one, if not I can upload the release and update the webpage.

**Comment by jasom** [comment]
@vsedach I don't have an account, and I e-mailed asking for one 6 days ago with no response, so you'll have to do this one I guess.

**Comment by jasom** [comment]
I now have an account, and updated the release on common-lisp.net
