### ISSUE TITLE
Bitwise operation dont work

### ISSUE THREAD

**Issue by svetlyak40wt** [vsedach/Parenscript#29]
For example:

```
CL-USER> (ps:ps (setf foo (& 2 3)))
"foo = &(2, 3);"
```

Expected result is:

```
foo = 2 & 3
```

The same with other similar operators:

```
CL-USER> (ps:ps (setf foo (^ 2 3)))
"foo = caret(2, 3);"
CL-USER> (ps:ps (setf foo (\| 2 3)))
"foo = |(2, 3);"
CL-USER> (ps:ps (setf foo (\|\| 2 3)))
"foo = ||(2, 3);"
CL-USER> (ps:ps (setf foo (&& 2 3)))
"foo = &&(2, 3);"
```

Parenscript version: 2.3

**Comment by PuercoPop** [comment]
Bitwise operators are called logand, logxor, in Parenscript, like CL. Why would you expect them to be named like the JS counter parts?

**Comment by svetlyak40wt** [comment]
@PuercoPop because I've read reference manual's section [Arithmetic and boolean operators](https://common-lisp.net/project/parenscript/reference.html#section-arithmetic):

```
* (<operator> {argument}*)
* (<single-operator> argument)

<operator>
one of *, /, %, +, -, <<, >>, >>>, < >, EQL, ==, !=, =, ===, !==, &, ^, |, &&, AND, ||, OR

<single-operator>
one of INCF, DECF, ++, --, NOT, !

argument
an expression

Operator forms are similar to function call forms, but have an operator as function name.

Please note that = is converted to == in JavaScript. The = Parenscript operator is not the assignment operator.

(* 1 2)
1 * 2;
(= 1 2)
1 === 2;
```

**Comment by PuercoPop** [comment]
https://github.com/vsedach/Parenscript/blob/master/src/package.lisp#L82 you can see the current API for bitwise operations in the package definition. 

Unfortunately the documentation is outdated, @jasom does updating the reference.hmtl in this repository update the c-l.net version?

**Comment by vsedach** [comment]
Updated the reference manual.
