### ISSUE TITLE
reduce ignores any "false" init argument

### ISSUE THREAD

**Issue by appleby** [vsedach/Parenscript#40]
## version

Parenscript version is 2.6 from quicklisp 2018-07-11.

## steps to reproduce

```
(ps:ps
  (ps:lisp ps:*ps-lisp-library*)
  (reduce (lambda (acc e) (min acc e)) '(1 2) 0))
```

When the resulting Javascript is evaluated, the call to `reduce` returns 1, not 0.

## description

The implementation of `reduce` in `ps-runtime-lib.lisp` looks like this:

```
(defun reduce (func list &optional init) ;; the use of init here is actually a bit broken wrt null
      (let* ((acc))
        (do* ((i (if init -1 0) (1+ i))
              (acc (if init init (elt list 0)) (func acc (elt list i))))
             ((>= i (1- (length list)))))
        acc))
```

The comment indicates that the `init` arg is broken w.r.t. `null`, but actually the `init` arg ends up being ignored if you pass anything Javascript considers "falsey".

Here are some examples of calling `reduce` from the Javascript console in Chrome dev tools. The last one is admittedly contrived.

```
> reduce((acc, e) => acc * e, [1,2,3,4,5], 0)
120 /* expect 0 */
> reduce((acc,e) => Math.min(acc, e), [1, 2], 0)
1 /* expect 0 */
> reduce((acc, e) => acc + e, [1.0, 2.0], NaN)
3 /* expect NaN */
> reduce((acc, e) => acc && e, [true,true,true], false)
true /* expect false */
> reduce((acc,e) => acc, ["foo", "bar"], "")
"foo" /* expect "" */
```

For reference, here is the corresponding Javascript version of `reduce` that is generated by Parenscript.

```
function reduce(func, list, init) {
    var acc = null;
    for (var i = init ? -1 : 0, acc = init ? init : list[0]; i < list.length - 1; i += 1, acc = func(acc, list[i])) {
    };
    return acc;
};
```

Of course, there is always Javascript's `Array.prototype.reduce` as a workaround for recent Javascript versions.

**Comment by vsedach** [comment]
Fixed in 963e71b

Thanks for the bug report!
