### ISSUE TITLE
Deprecation warning for symbols with embedded dot (.) or bracket ([]) chars only triggered if symbol also contains one of -*+!?#@%/=:<>^

### ISSUE THREAD

**Issue by appleby** [vsedach/Parenscript#41]
## version

Parenscript version is 2.6 from quicklisp 2018-07-11.

## steps to reproduce

In the below repl session, I would assume the intention is to also issue a deprecation warning for `foo.bar` and `foobar[3]`.

```
CL-USER> (ps:ps foo.bar)
"foo.bar;"
CL-USER> (ps:ps foo.bar?)
WARNING: Symbol FOO.BAR? contains one of '.[]' - this compound naming convention is no longer supported by Parenscript!
"foo.barwhat;"
CL-USER> (ps:ps foobar[3])
"foobar[3];"
CL-USER> (ps:ps foo-bar[3])
WARNING: Symbol FOO-BAR[3] contains one of '.[]' - this compound naming convention is no longer supported by Parenscript!
"fooBar[3];"
```

## description

The implementation of `ps::encode-js-identifier` in `utils.lisp` issues a deprecation warning if the user creates an identifier with an embedded dot (.) or sqaure brackets ([]); however, `ps::encode-js-identifier` will only issue the warning about embedded dot and/or square brackets if certain other special characters are present in the identifier name which cause Parenscript name mangling rules to kick in. I assume this is a bug, and the intention is to always warn about embedded dot/bracket characters?

Here is the relevant portion of `ps::encode-js-identifier`.

```
(let ((cache (make-hash-table :test 'equal)))
  (defun encode-js-identifier (identifier)
    "Given a string, produces to a valid JavaScript identifier by
following transformation heuristics case conversion. For example,
paren-script becomes parenScript, *some-global* becomes SOMEGLOBAL."
    (or (gethash identifier cache)
        (setf (gethash identifier cache)
              (cond ((some (lambda (c) (find c "-*+!?#@%/=:<>^")) identifier)
                     (let ((lowercase t)
                           (all-uppercase nil))
                       (when (and (not (string= identifier "[]")) ;; HACK
                                  (find-if (lambda (x) (find x '(#\. #\[ #\]))) identifier))
                         (warn "Symbol ~A contains one of '.[]' - this compound naming convention is no longer supported by Parenscript!"
                               identifier))
                         ...
```

If I understand correctly:

- the `cond` test ensures that `identifier` contains at least one of the characters `-*+!?#@%/=:<>^`
  - therefore, the `(string= identifier "[]")` test can never be true
  - therefore, the warning about an identifier containing a period and/or square brackets can only be triggered if it also contains one of the characters `-*+!?#@%/=:<>^`

**Comment by vsedach** [comment]
Looks like I broke that in 4d833e721f78796943d0f4a5be33734c839e3c1a. Pushed a fix just now: https://github.com/vsedach/Parenscript/commit/d11e2ec2864976c6c9dc5da4ced88bfacbddfe4e

Thank you very much for the bug report!
