### ISSUE TITLE
PS adds a semicolon after function declarations

### ISSUE THREAD

**Issue by ralt** [vsedach/Parenscript#7]
Simple example:

```
CL-USER> (ps:ps (defun test ()))
"function test() {
    return null;
};"
```

Is this by design? It's completely useless in this case.

It's not that it bothers, since it just creates a new empty statement, but I'm wondering if it should be considered a bug.

**Comment by jasom** [comment]
This is a semicolon that would need to be added by ASI anyway, so it's not a bug.  My reading of the ECMA standard is that a function declaration is an expression, not a statement, which would require a semicolon at the end to make it a statement, as intended in your example.

**Comment by ralt** [comment]
Well, function declarations are weird, they're neither an expression nor a statement.

A small snippet:

```
> function test(){} var foo = 'foo';
undefined
> (function test(){}) var foo = 'foo';
Uncaught SyntaxError: Unexpected token var(…)
```

Anyway, it's not a bug in that it's a useless semicolon that doesn't do any harm. It's a bug in that it's a useless semicolon :-)

ASI is definitely not an issue in this case though.
